[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.vim/dein/plugins/quickrun.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = '''
  let indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 0
  let g:indent_guides_color_change_percent = 90
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
  let g:indent_guides_space_guides = 1
  let g:indent_guides_exclude_filetypes = ['help', 'nerdtree',
    \ 'vimfiler', 'quickfix', 'unite', 'go']
'''
hook_add = '''
  augroup MyAutoCmd
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=60
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=236
  augroup END
'''

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <Leader>gs :<C-u>Gstatus<Enter>
  nnoremap <Leader>gb :<C-u>Gblame<Enter>
'''

[[plugins]]
repo = 'cohama/agit.vim'
hook_add = '''
  nnoremap <Leader>gv :<C-u>AgitFile<Enter>
'''

[[plugins]]
repo = 'jimsei/winresizer'
hook_source = '''
  let g:winresizer_enable = 1
  let g:winresizer_start_key = '<C-E>'
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  if !exists('g:airline_symbols')
    let g:airline_symbols = {}
  endif
  let g:airline_theme = 'molokai'
  let g:airline_detect_iminsert = 1

  let g:airline#extensions#branch#enabled = 1
  let g:airline#extensions#branch#format = 1

  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#show_buffers = 0
  let g:airline#extensions#tabline#tab_nr_type = 1

  let g:airline#extensions#whitespace#enabled = 1
  let g:airline#extensions#whitespace#mixed_indent_algo = 1
  let g:airline_symbols.whitespace = 'Îž'

  let g:airline#extensions#ale#enabled = 1
  let airline#extensions#ale#error_symbol = 'E:'
  let airline#extensions#ale#warning_symbol = 'W:'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'

[[plugins]]
repo = 'joedicastro/vim-molokai256'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tlhr/anderson.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'

[[plugins]]
repo = 'tpope/vim-obsession'
