[ftplugin]
_ = '''
  " Disable automatically insert comment.
  setl formatoptions-=r
  setl formatoptions-=o
  setl formatoptions+=mMBl
  " Disable auto wrap.
  if &l:textwidth != 70 && &filetype !=# 'help'
    setlocal textwidth=0
  endif
  " Use FoldCCtext().
  if &filetype !=# 'help'
    setlocal foldtext=FoldCCtext()
  endif
  if !&l:modifiable
    setlocal nofoldenable
    setlocal foldcolumn=0
    setlocal colorcolumn=
  endif
'''

go = '''
  setlocal noexpandtab tabstop=4 shiftwidth=4
  highlight default link goErr WarningMsg
  match goErr /\<err\>/
'''

help = '''
  setlocal iskeyword+=:
  setlocal iskeyword+=#
  setlocal iskeyword+=-
'''

html = '''
  setlocal includeexpr=substitute(v:fname,'^\\/','','')
  setlocal path+=./;/
'''

javascript = '''
  setlocal shiftwidth=2 softtabstop=2 tabstop=2
'''

php = '''
  setlocal shiftwidth=4 softtabstop=4 tabstop=4
'''

python = '''
  " Indent settings.
  setlocal foldmethod=indent
  setlocal softtabstop=4
  setlocal shiftwidth=4
  setlocal textwidth=80
  setlocal nosmartindent
'''

qfreplace = '''
  setlocal nofoldenable
'''

ruby = '''
  setlocal iskeyword+=!
  setlocal iskeyword+=?
  setlocal omnifunc=
  setlocal shiftwidth=2 softtabstop=2 tabstop=2
'''

sh = '''
  setlocal shiftwidth=2 softtabstop=2 tabstop=2
'''

sql = '''
  setlocal shiftwidth=2 softtabstop=2 tabstop=2
'''

toml = '''
  syntax sync minlines=500
'''

vim = '''
  if line('$') > 1000
    syntax sync minlines=200
  endif
  setlocal foldmethod=indent
  setlocal shiftwidth=2 softtabstop=2
  setlocal iskeyword+=:,#
'''

yaml = '''
  setlocal shiftwidth=2 softtabstop=2 tabstop=2
'''

zsh = '''
  setlocal shiftwidth=2 softtabstop=2 tabstop=2
'''
